# config.yml

backend:
  name: github
  repo: MrinmoyHaloi/Callisto-Analytics
media_folder: 'images'
collections:
  - label: "services"
    name: "services"
    folder: "_services/"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "blogs"
    name: "blogs"
    folder: "_blogs/"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}